/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Debt: {
            /** Format: uuid */
            id: string;
            /** @description Nombre de la deuda (ej. Tarjeta de Crédito, Préstamo Vehicular) */
            name: string;
            /** @description Saldo actual. Usar string para preservar precisión decimal. */
            currentBalance: string;
            /** @description Tasa Efectiva Anual (EA) en formato decimal (ej. 0.15 para 15%). Usar string para precisión. */
            effectiveAnnualRate: string;
            /**
             * Format: date
             * @description Fecha de corte.
             */
            cutoffDate: string;
        };
        Investment: {
            /** Format: uuid */
            id: string;
            /** @description Nombre del instrumento de inversión (ej. CDT, Acciones) */
            name: string;
            /** @description Saldo actual o monto invertido. Usar string para preservar precisión decimal. */
            currentBalance: string;
            /** @description Tasa Efectiva Anual (EA) de rendimiento esperada. */
            effectiveAnnualRate: string;
            /**
             * Format: date
             * @description Fecha de corte o apertura.
             */
            cutoffDate: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
